region: eu-west-1
hostport: 80
containerport: 80
app_name: assets
role: frontend-apps
environment: prod
iac: terraform-workspace-aws-test-applications-eu-west-1-apps-assets-prod-polygon-technology
team_name: product-apps
memory: 1024
cpu: 512
