region: eu-west-1
account_number: "070528468658"
hostport: 3000
containerport: 3000
app_name: wallet-asset-prod
role: frontend-apps
environment: prod
iac: terraform-workspace-aws-prod-applications-eu-west-1-apps-wallet-asset-prod-polygon-technology
team_name: product-apps
memory: 1024
cpu: 512
