region: eu-west-1
account_number: "070528468658"
hostport: 80
containerport: 80
app_name: assets-prod
role: frontend-apps
environment: prod
iac: terraform-workspace-aws-prod-applications-eu-west-1-apps-assets-prod-polygon-technology
team_name: product-apps
memory: 1024
cpu: 512
