name: Wallet Asset Production Deployment
on:
  push:
    branches:
    - DEVOPS-1384-update-secrets-based-auth
  workflow_dispatch:

jobs:
  build:
   name: Wallet Asset Production
   permissions:
    id-token: write
    contents: write
   environment: production
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::042947190491:role/wallet-asset-GithubActionsRole
        role-session-name: GitHubActionsSession

    - name: Deploy to S3 bucket
      run: aws s3 sync ./assets/ s3://${{ secrets.PROD_AWS_S3_BUCKET }} --acl public-read --delete
    
    - name: invalidate cloudfront distribution and wait for completion
      uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
      env:
         DISTRIBUTION_ID: ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }}
         PATHS: "/*"
         AWS_REGION: "eu-west-1"
